### ISSUE TITLE
Double-check that specialization enumerations match w/ Karl’s published CMIP6 CVs.

### ISSUE THREAD

**Issue by allynt** [ES-DOC/cmip6-specializations-toplevel#4]
Double-check that specialization enumerations match w/ Karl’s published CMIP6 CVs.

[https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_realm.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_realm.json)

**Comment by eguil** [comment]
checked
