### ISSUE TITLE
Ensure that all CIM2 schema-level properties are included in CMIP6 specializations

### ISSUE THREAD

**Issue by allynt** [ES-DOC/cmip6-specializations-toplevel#5]
Ensure that all CIM2 schema-level properties are included in CMIP6 specialization config files.

**Comment by allynt** [comment]
This can either be handled by having @momipsl extend his code to do this automatically or by just using a "template" specialization config file that includes all the schema-level properties which can then be refined (this is preferred by everybody).

**Comment by allynt** [comment]
What happens, though, if a CIM2 schema property has cardinality 1.N but a specialization overrides that to be 0.N.  This correctly tells downstream tools not to render that property.  But in the long-term won't this create an invalid CIM2 document?

**Comment by eguil** [comment]
Do we still need this ?
