### ISSUE TITLE
Add tuning section

### ISSUE THREAD

**Issue by eguil** [ES-DOC/cmip6-specializations-toplevel#7]
Reconcile CIM2 tuning class with [Hourdin et al. BAMS 2016](http://journals.ametsoc.org/doi/abs/10.1175/BAMS-D-15-00135.1). Namely, in conclusion:

`Because tuning will affect the behavior of a climate model, and the confidence that can be given to a partic- ular use of that model, it is important to document the tun- ing portion of the model development process. We rec- ommend distinguishing three levels in the tuning process: individual parameterization tuning, component tuning and climate system tuning. The strategy followed at each level should be documented, explaining and the motivating the main targets and metrics retained. At the component level, emphasis should be put on the relative weight given to cli- mate performance metrics versus process oriented metrics, and on the possible conflicts with parameterization level tuning. For the climate system tuning, particular emphasis should be put on the way energy balance was obtained in the full system: was it done by tuning the various com- ponents independently, or was some final tuning needed? The degree to which the observed trend of the 20th century was used or not for tuning should also be described. Com- parisons against observations, and adjustment of forcing or feedback processes should be noted. At each step, any occasion where a team had to struggle with a parameter value or push it to its limits to solve a particular model de- ficiency should be emphasized. This information may well be scientifically valuable as a record of the uncertainty of a model formulation.`

**Comment by eguil** [comment]
Here is the tuning class:

```
def tuning():
    """Method used to optimise equation parameters in model component
    (aka 'tuning').
    """
    return {
        'type': 'class',
        'base': 'science.sub_process',
        'is_abstract': False,
        'properties': [
            ('description', 'str', '1.1',
                "Brief description of tuning methodology. Include information about observational period(s) used."),
            ('global_mean_metrics_used', 'data.variable_collection', '0.1',
                "Set of metrics of the global mean state used in tuning model parameters."),
            ('regional_metrics_used', 'data.variable_collection', '0.1',
                "Which regional metrics of mean state (e.g Monsoons, tropical means etc) have been used in tuning."),
            ('trend_metrics_used', 'data.variable_collection', '0.1',
                "Which observed trend metrics have been used in tuning model parameters.")
        ],
        'constraints': [
            ('cardinality', 'implementation_overview', '0.0'),
        ]
    }
```

**Comment by eguil** [comment]
As always, we can update the CIM to have more precise question or leave those to the specialisation (but then have to merge the CIM and specialisation questions in an organised way)

**Comment by davidhassell** [comment]
For completeness, we also get these properties via inheritance from `science.subprocess` and `science.scientific_context`:

```
            ('description', 'str', '1.1',
                "Scientific context for which this description is provided."),
            ('short_name', 'str', '1.1',
                "The name of this process/algorithm/sub-process/detail.")
            ('citations', 'shared.citation', '0.N',
                "Set of pertinent citations."),
            ('details', 'science.detail', '0.N',
               "Sets of properties for this process."),
```

**Comment by eguil** [comment]
Added top_level and realm level questions about tuning following Hourdin et al. 2016
